fix: source require.sh

diff --git a/gitcheckoutbranches b/gitcheckoutbranches
--- a/gitcheckoutbranches
+++ b/gitcheckoutbranches
@@ -26,6 +26,10 @@ source "${SCRIPT_DIR}/git.sh" || {
   echo "Failed to source git utilities" >&2
   exit 1
 }
+source "${SCRIPT_DIR}/require.sh" || {
+  echo "Failed to source require utilities" >&2
+  exit 1
+}
 
 #######################################
 # Print usage information
