fix: add check to see if submodules are owned by user or not.

diff --git a/gitsubmodules b/gitsubmodules
--- a/gitsubmodules
+++ b/gitsubmodules
@@ -69,38 +69,39 @@ attach_submodules() {
   readarray -t submodules < <(git submodule foreach --recursive | cut -d' ' -f2 | sed "s/^'\|'$//g")
 
   # Loop through each submodule
-  for submodule in "${submodules[@]}"; do
-    orig_dir="$(pwd)"
-    cd "$submodule"
-    main_br="$(main_branch)"
-    git checkout "$main_br"
-    git pull origin "$main_br"
-    # update local and remote repos only if owned by user
-    local is_own_repo
-    is_own_repo="$(check_remote_url "$GIT_USER")"
-    if "$is_own_repo"; then
-      git add .
-      # check if submodule is dirty i.e., files have been changed
-      added_files="$(git status --porcelain | awk -F, 'NF>0 {print $2}')"
-      if [ -n "${added_files}" ]; then
-        git commit -m "Added local files ${added_files} to submodule"
-        git push
-      fi
-    fi
-    if branch_exists "development"; then
-      git checkout development
-      git pull origin development
+  (
+    for submodule in "${submodules[@]}"; do
+      orig_dir="$(pwd)"
+      cd "$submodule"
+      main_br="$(main_branch)"
+      git checkout "$main_br"
+      git pull origin "$main_br"
       # update local and remote repos only if owned by user
-      if "$is_own_repo"; then
-        git merge "$main_br"
-        git push
+
+      if check_remote_url "$GIT_USER"; then
+        git add .
+        # check if submodule is dirty i.e., files have been changed
+        added_files="$(git status --porcelain | awk -F, 'NF>0 {print $2}')"
+        if [ -n "${added_files}" ]; then
+          git commit -m "Added local files ${added_files} to submodule"
+          git push
+        fi
       fi
-    fi
-    if ! $is_own_repo; then
-      printf "Warning: Submodule %s cannot be updated since it's an external dependency." "$submodule"
-    fi
-    cd "$orig_dir"
-  done
+      if branch_exists "development"; then
+        git checkout development
+        git pull origin development
+        # update local and remote repos only if owned by user
+        if check_remote_url "$GIT_USER"; then
+          git merge "$main_br"
+          git push
+        fi
+      fi
+      if ! check_remote_url "$GIT_USER"; then
+        printf "Warning: Submodule %s cannot be updated since it's an external dependency.\n" "$submodule"
+      fi
+      cd "$orig_dir"
+    done
+  )
 
   git submodule update --remote
   return 0
