fix: add check to see if submodules are owned by user or not.

diff --git a/gitsubmodules b/gitsubmodules
--- a/gitsubmodules
+++ b/gitsubmodules
@@ -7,7 +7,6 @@
 # @copyright   : Copyright (c) Linus Fernandes
 # @description : Automates update of git submodules in parent repo
 ######################################################################
-set -x
 set -euo pipefail
 shopt -s inherit_errexit
 RED="\033[0;31m"
@@ -55,6 +54,17 @@ branch_exists() {
   fi
 }
 
+check_remote_url() {
+  local user_id=$1
+  local remote_url
+  remote_url=$(git config --get remote.origin.url)
+  if [[ $remote_url == *"$user_id"* ]]; then
+    return 0
+  else
+    return 1
+  fi
+}
+
 attach_submodules() {
   readarray -t submodules < <(git submodule foreach --recursive | cut -d' ' -f2 | sed "s/^'\|'$//g")
 
@@ -65,17 +75,29 @@ attach_submodules() {
     main_br="$(main_branch)"
     git checkout "$main_br"
     git pull origin "$main_br"
-    git add .
-    # check if submodule is dirty i.e., files have been changed
-    added_files="$(git status --porcelain | awk -F, 'NF>0 {print $2}')"
-    if [ -n "${added_files}" ]; then
-      git commit -m "Added local files ${added_files} to submodule"
-      git push
+    # update local and remote repos only if owned by user
+    local is_own_repo
+    is_own_repo="$(check_remote_url "$GIT_USER")"
+    if "$is_own_repo"; then
+      git add .
+      # check if submodule is dirty i.e., files have been changed
+      added_files="$(git status --porcelain | awk -F, 'NF>0 {print $2}')"
+      if [ -n "${added_files}" ]; then
+        git commit -m "Added local files ${added_files} to submodule"
+        git push
+      fi
     fi
     if branch_exists "development"; then
       git checkout development
       git pull origin development
-      git merge "$main_br"
+      # update local and remote repos only if owned by user
+      if "$is_own_repo"; then
+        git merge "$main_br"
+        git push
+      fi
+    fi
+    if ! $is_own_repo; then
+      printf "Warning: Submodule %s cannot be updated since it's an external dependency." "$submodule"
     fi
     cd "$orig_dir"
   done
